### ISSUE TITLE
InvalidARNError: invalid ARN

### ISSUE THREAD

**Issue by ArteChp** [NoEnv/drone-s3-sync#1]
Hello, could you clarify what is a correct format of S3 bucket?

For just name "data-1", I have:

```
s3sync-1     | Synchronizing with bucket "wordpress-database-1"
s3sync-1 exited with code 0
```

For ARN "arn:aws:s3:::data-1":

```
s3sync-1 exited with code 1
s3sync-1 exited with code 1
s3sync-1     | InvalidARNError: invalid ARN
s3sync-1     | caused by: invalid Amazon s3 ARN, unknown resource type, arn:aws:s3:::data-1
```
For "s3://data-1":

```
s3sync-1     | InvalidBucketName: The specified bucket is not valid.
s3sync-1     | 	status code: 400, request id: BDEMKS887S87EC, host id: HKevONrUCnDY4yi968fA9j/M05zPa3ZRgSKDKs77ss9YlT8pE0U7k2y9Yz8i9dko=
s3sync-1 exited with code 1
```

**Comment by zyclonite** [comment]
simply the bucket name like in your first example... it's only weird that you use data-1 and the message refers to a wordpress bucket

**Comment by ArteChp** [comment]
Got it, thanks. I'll try to debug why it doesn't work for me.
I forgot to edit and replace the name "wordpress-database-1" before posting.
