### ISSUE TITLE
Support Docker Secrets

### ISSUE THREAD

**Issue by ArteChp** [NoEnv/drone-s3-sync#2]
Hello,
I'm trying to use Docker secrets by the doc https://docs.docker.com/compose/use-secrets/ and it doesn't work.

When I'm using environment
```
      AWS_ACCESS_KEY_ID: /run/secrets/aws_access_key_id 
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws_secret_access_key 
```
It doesn't extract these secrets on the fly. 

Then I tried to export these secrets with sh:
```
entrypoint: /bin/sh -c "export AWS_ACCESS_KEY_ID=$(</run/secrets/aws_access_key_id); export AWS_SECRET_ACCESS_KEY=$(</run/secrets/aws_secret_access_key);  /bin/drone-s3-sync"
```
and I had the error:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```
I suppose the Alpine container hasn't installed sh.

Could you suggest a right approach without building with modified Dockerfile?

**Comment by zyclonite** [comment]
i would recommend using secrets as described in the drone.io docs https://docs.drone.io/secret/

or global ones via https://docs.drone.io/runner/docker/configuration/reference/drone-runner-secrets/

**Comment by ArteChp** [comment]
Thank you
